{% set name = "ome-zarr" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ome-zarr-{{ version }}.tar.gz
  sha256: 755a3ef85b0f15ab7c82b699a3f4849573c54850b21ca9b61044b6fd1bb3df5f

build:
  number: 0
  noarch: python
  entry_points:
    - ome_zarr = ome_zarr.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - aiohttp
    - dask-core
    - fsspec !=2021.07.0
    - numpy
    - python >=3.7
    - requests
    - scikit-image
    - toolz
    - zarr >=2.8.1

test:
  imports:
    - ome_zarr
  commands:
    - pip check
    - ome_zarr --help
  requires:
    - pip

about:
  home: https://github.com/ome/ome-zarr-py
  summary: Implementation of images in Zarr files.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - constantinpape
    - joshmoore
    - k-dominik
