{% set name = "ome-zarr" %}
{% set version = "0.12.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a3a47d265e35463ad04b0572776605cff69198ddae971e83a98f1ac4ee5b83e7

build:
  number: 0
  noarch: python
  entry_points:
    - ome_zarr = ome_zarr.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8.0
  run:
    - aiohttp <4
    - dask-core
    - distributed
    - fsspec >=0.8,!=2021.07.0,!=2023.9.0
    - numpy
    - python >={{ python_min }}
    - requests
    - scikit-image >=0.19.0
    - toolz
    - zarr >=v3.0.0

test:
  imports:
    - ome_zarr
  commands:
    - python -c "import importlib.metadata; print(importlib.metadata.version('ome_zarr'))" | grep -q {{ version }}
    - pip check
    - ome_zarr --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ome/ome-zarr-py
  summary: Implementation of images in Zarr files.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - constantinpape
    - joshmoore
    - k-dominik
    - jdblischak
